/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package no.norrs.projects.andronary;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int button_clear=0x7f050004;
        public static final int button_dictonary=0x7f050003;
        public static final int button_query=0x7f050005;
        public static final int history=0x7f050000;
        public static final int main_ask=0x7f050001;
        public static final int password=0x7f05000a;
        public static final int query=0x7f050002;
        public static final int text1=0x7f050006;
        public static final int text2=0x7f050007;
        public static final int text3=0x7f05000b;
        public static final int url=0x7f050009;
        public static final int username=0x7f050008;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int search_result_list_view=0x7f030001;
        public static final int search_result_row_view=0x7f030002;
        public static final int settings=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
